export const ACCEPT_REQUEST = "ACCEPT_REQUEST";
export const GENERATE_INVOICE="GENERATE_INVOICE";
export const GET_ALL_REQUESTS="GET_ALL_REQUESTS";
export const GET_ALL_PAYMENTS="GET_ALL_PAYMENTS";
export const GET_ALL_SERVICES="GET_ALL_SERVICES";